export const TOGGLE_SIDEBAR_VISIBILITY = "TOGGLE_SIDEBAR_VISIBILITY";

export const TOGGLE_LOGIN_FORM_VISIBILITY = "TOGGLE_LOGIN_FORM_VISIBILITY";
export const TOGGLE_LOGIN_FORM_LOADING = "TOGGLE_LOGIN_FORM_LOADING";

export const TOGGLE_RESTORE_PASSWORD_FORM_VISIBILITY =
  "TOGGLE_RESTORE_PASSWORD_FORM_VISIBILITY";
export const TOGGLE_RESTORE_PASSWORD_FORM_LOADING =
  "TOGGLE_RESTORE_PASSWORD_FORM_LOADING";

export const TOGGLE_SIGN_UP_FORM_VISIBILITY = "TOGGLE_SIGN_UP_FORM_VISIBILITY";
export const TOGGLE_SIGN_UP_FORM_LOADING = "TOGGLE_SIGN_UP_FORM_LOADING";

export const TOGGLE_SEARCH_FORM_VISIBILITY = "TOGGLE_SEARCH_FORM_VISIBILITY";

export const UPDATE_USERNAME_IN_FORM_LOGIN = "UPDATE_USERNAME_IN_FORM_LOGIN";
export const UPDATE_PASSWORD_IN_FORM_LOGIN = "UPDATE_PASSWORD_IN_FORM_LOGIN";

export const UPDATE_THREAD_LIST = "UPDATE_THREAD_LIST";
export const UPDATE_SCROLLED_PAGE_COUNT = "UPDATE_SCROLLED_PAGE_COUNT";
export const UPDATE_BANNER_LIST = "UPDATE_BANNER_LIST";
export const UPDATE_RECAPTCHA = "UPDATE_RECAPTCHA";
export const UPDATE_FINGERPRINT = "UPDATE_FINGERPRINT";
