export const TOGGLE_SIDEBAR_VISIBILITY = "TOGGLE_SIDEBAR_VISIBILITY";
export const TOGGLE_SEARCH_FORM_VISIBILITY = "TOGGLE_SEARCH_FORM_VISIBILITY";
export const UPDATE_THREAD_LIST = "UPDATE_THREAD_LIST";
export const UPDATE_SCROLLED_PAGE_COUNT = "UPDATE_SCROLLED_PAGE_COUNT";
export const UPDATE_BANNER_LIST = "UPDATE_BANNER_LIST";
