// export const TOGGLE_SIDEBAR_VISIBILITY = "TOGGLE_SIDEBAR_VISIBILITY";
//
// // Формы
// // Авторизация
// export const TOGGLE_LOGIN_FORM_VISIBILITY = "TOGGLE_LOGIN_FORM_VISIBILITY";
// export const TOGGLE_LOGIN_FORM_LOADING = "TOGGLE_LOGIN_FORM_LOADING";
// export const UPDATE_EMAIL = "UPDATE_EMAIL";
// export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
//
// // Восстановление пароля
// export const TOGGLE_FORM_VISIBILITY =
//   "TOGGLE_FORM_VISIBILITY";
// export const TOGGLE_FORM_LOADING =
//   "TOGGLE_FORM_LOADING";
// export const UPDATE_EMAIL =
//   "UPDATE_EMAIL";
//
// // Регистрация
// export const TOGGLE_SIGN_UP_FORM_VISIBILITY = "TOGGLE_SIGN_UP_FORM_VISIBILITY";
// export const TOGGLE_SIGN_UP_FORM_LOADING = "TOGGLE_SIGN_UP_FORM_LOADING";
// export const UPDATE_USERNAME =
//   "UPDATE_USERNAME";
// export const UPDATE_EMAIL = "UPDATE_EMAIL";
// export const TOGGLE_SUBSCRIBE =
//   "TOGGLE_SUBSCRIBE";
// export const TOGGLE_RULES = "TOGGLE_RULES";
//
// export const TOGGLE_SEARCH_FORM_VISIBILITY = "TOGGLE_SEARCH_FORM_VISIBILITY";
//
// export const UPDATE_THREAD_LIST = "UPDATE_THREAD_LIST";
// export const UPDATE_SCROLLED_PAGE_COUNT = "UPDATE_SCROLLED_PAGE_COUNT";
// export const UPDATE_BANNER_LIST = "UPDATE_BANNER_LIST";
// export const UPDATE_RECAPTCHA = "UPDATE_RECAPTCHA";
// export const UPDATE_FINGERPRINT = "UPDATE_FINGERPRINT";
